name: git_checkout_and_push_tmpl

on: workflow_call

jobs:
  Pull_And_Push:
    runs-on: ubuntu-latest 
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call script for push to "${{ github.repository }}"
        run: | 
            chmod +x .scripts/push_to_repo.sh
            .scripts/push_to_repo.sh
