name: Main CI File

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: 

jobs:
  Update-Homepage:
    uses: ./.github/workflows/github-tmpl-update-apache-homepage.yml
    with:
      environment: stage
      name: vasya
      page_text: Hello from reusable workflow
        
