name: Main CI File
# github-tmpl-update-apache-homepage pipeline template, accept the following input parameters: environment, page_text, and name.
# This template is triggered both from another pipeline and manually from the UI.
# The template validates the input parameters, and if the environment value is not provided, it stops execution with a specific error message.
# If name or page_text are not provided, default values is assigned.

# When manually triggered:
#	1. The environment is selected from: development, stage, prod.
#	2. The name field is a text input with a default value of "Vlad".
#	3. The page_text field is a text input with a default value of "Привет из шаблона пайплайна".

# The main pipeline should be triggered based on the following conditions:
#	• A push to the main branch
#	• A MergeRequest event

# The main pipeline should trigger the template workflow with the following parameters:
# environment: "dev"  
# name: "vasya"  
# page_text: "Hello from reusable workflow" 

# The values of these variables should be inserted into the Apache homepage, which is generated dynamically.

# This step should only be triggered if:
#	• The fake unit tests (a separate pipeline step) pass successfully.
#	• The environment is not "prod".

on:
  push:
    branches: 
     - main
  pull_request:
    types: 
     - closed #triggre workflow if PR is merged. 
    branches: 
     - main
  workflow_dispatch: 

jobs:
  Update-Homepage:
    uses: ./.github/workflows/github-tmpl-update-apache-homepage.yml
    with:
      environment: development
      name: "vasya"
      page_text: "Hello from reusable workflow"
        
