name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  push_to_repo:
    runs-on: ubuntu-latest
    env:
        WORK_DIR: "/tmp/Repo"
    
    steps:
      - name: make work dir
        run: mkdir -p "${{ env.WORK_DIR }}" && cd "${{ env.WORK_DIR }}"
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call script for push to "${{ github.repository }}"
        env: 
          GIT_USER: "vlad_bars"
          GIT_USER_EMAIL: "vlad_bars@gmails.com"
          REPO_DIR: "${{ env.WORK_DIR }}/GithubActions" 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GIT_NAME: ${{ github.repository }}
        run: | 
            chmod +x .scripts/push_to_repo.sh
            .scripts/push_to_repo.sh
         
   
 

