name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  push_to_repo:
    runs-on: ubuntu-latest
    env:
        WORK_DIR: "/tmp/Repo"
    
    steps:
      - name: make work dir
        run: mkdir -p "${{ env.WORK_DIR }}" && cd "${{ env.WORK_DIR }}"
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permissions
        run: chmod +x .scripts/push_to_repo.sh

      - name: Call script
        env: 
          GIT_USER: "vlad_bars"
          GIT_USER_EMAIL: "vlad_bars@gmails.com"
          REPO_DIR: "${{ env.WORK_DIR }}/GithubActions"        
        run: .scripts/push_to_repo.sh
         
   
 

