name: pull_and_push_to_repo

on:
  push:
    branches:
      - main

jobs:
  pull_and_push_to_repo:
    runs-on: ubuntu-latest 
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call script for push to "${{ github.repository }}"
        run: | 
            chmod +x .scripts/push_to_repo.sh
            .scripts/push_to_repo.sh
         
   
 

