name: pull_and_push_to_repo

on:
  push:
    branches:
      - main

jobs:
 Clone_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
              
      - name: push to repo
        run: bash .scripts/push_to_repo.sh
   
 

