on:
 push:
   branches:
   - main
 pull_request:
   branches:
   - main

jobs:
  create_repo:
    name: create_repo
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_NAME: Vlad
      run: |
        echo "Hello $MY_NAME"
    

  push_to_repo:
     name: push
     runs-on: ubuntu-latest
     steps:
       - name: call script
         env: 
           WORK_DIR: "/tmp/Repo"
           REPO_URL: "https://$GIT_TOKEN@github.com/VBaranouski/DevopsPath.git"
           GIT_USER: "vlad_bars"
           GIT_USER_EMAIL: "vlad_bars@gmails.com"
           REPO_DIR: "$WORK_DIR/DevopsPath"        
         run: bash ./scritps/push_to_repo.sh
         
   
 

