name: pull_and_push_to_repo

on:
  push:
    branches:
      - main

jobs:
 Clone_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make test folder
        run: | 
              mkdir Test 
              cd Test
              touch test.txt
              
      - name: push to repo
        uses: ./.github/workflows/git_checkout_and_push_tmpl.yml
   
 

