name: pull_and_push_to_repo

on:
  push:
    branches:
      - dev

jobs:
 Clone_And_Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
              
      - name: push to "${{ github.repository }}" repo
        run: bash .scripts/push_to_repo.sh
   
 

